"""add unique "isbn" column to books table

Revision ID: 6c2b9edcd28b
Revises: eee8eea91bc3
Create Date: 2025-08-16 07:31:51.118690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer
from app.utils.isbn import generate_fake_isbn


# revision identifiers, used by Alembic.
revision: str = '6c2b9edcd28b'
down_revision: Union[str, Sequence[str], None] = 'eee8eea91bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))

    books_table = table(
        'books',
        column('id', Integer),
        column('isbn', String),
    )
    conn = op.get_bind()
    result = conn.execute(sa.select(books_table.c.id)).fetchall()

    for row in result:
        conn.execute(
            books_table.update()
            .where(books_table.c.id == row.id)
            .values(isbn=generate_fake_isbn())
        )

    op.alter_column('books', 'isbn', nullable=False)

    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
