"""Add format column to books

Revision ID: c872e5379a47
Revises: 4b5f94fcaf38
Create Date: 2025-08-12 15:16:21.527960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c872e5379a47'
down_revision: Union[str, Sequence[str], None] = '4b5f94fcaf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('format', sa.String(), nullable=False, server_default='paperback'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'format')
    # ### end Alembic commands ###
